version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    command: >
      sh -c "./start_xvfb.sh
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    environment:
      - DISPLAY=:10

  celery:
    build:
      context: .
      dockerfile: celery/Dockerfile
    container_name: celery
    command: celery -A home.celery worker -l ERROR -E
    volumes:
      - ./app:/app
    depends_on:
      - django
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: celery/Dockerfile
    container_name: celery-beat
    command: celery -A home.celery beat -l ERROR
    volumes:
      - ./app:/app
    depends_on:
      - django
      - redis
      - celery

  redis:
    container_name: redis
    image: "redis:alpine"
    depends_on:
      - django
